### ISSUE TITLE
NTP settings

### ISSUE THREAD

**Issue by iqqmuT** [rameplayerorg/rameplayer-webui#10]
Add to settings:
- NTP server hostname / IP
- timezone setting
- local time setting if NTP not configured

**Comment by viliman** [comment]
focusing on setting NTP server hostname / IP and local time if NTP not configured (skipping timezone and sticking for UTC at the moment)

**Comment by viliman** [comment]
@foliharp local time needs to include seconds so one more input field for seconds needed

**Comment by viliman** [comment]
This is done
