### ISSUE TITLE
Wrong type of field posted for logging

### ISSUE THREAD

**Issue by jlauha** [rameplayerorg/rameplayer-webui#23]
Webui console shows:
"Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)"
Backend responds for "invalid value for parameter: time"
Don't know if issue is in backend or webui.

**Comment by iqqmuT** [comment]
Fixed in backend:
https://github.com/rameplayerorg/rameplayer-backend/commit/09b401013b24f82506c04af01c547f5f815b7392
