### ISSUE TITLE
Continuous refresh loop after firmware upgrade and cluster config

### ISSUE THREAD

**Issue by jlauha** [rameplayerorg/rameplayer-webui#27]
Web UI went to continuous refresh loop after roughly doing following:
(using latest Chrome browser on Windows 7)

1. Upgraded to firmware: dev-20160323 (Web UI version: v0.7.0)
2. Did misc. backend development, i.e. backend is later than what was in firmware
3. Possibly same Rame got development version of webui as well
4. (time passes / other testing)
5. Created a playlist to this Rame and another R.Pi
6. Went to configure a cluster - entered IP for other R.Pi, pressed "Add" next to Play Delay.
** At this point Web UI started continuously and rapidly refreshing the Web UI, with the "Firmware upgraded" info toasters popping up after each refresh **

Additional notes:
- Problem goes away after clearing Local Storage from browser. But it starts again if trying to setup the cluster again as in step 6.
- Even when refresh issue was undergoing, same issue didn't reappear in different browser.
- Apparently the other R.Pi. has different backend version

(used "Report a problem" + passed example video & screenshot separately)

**Comment by iqqmuT** [comment]
Fixed with commit above.
I was able to reproduce the bug, two clusters with different firmware versions caused it.

**Comment by jlauha** [comment]
Seems to work with the latest build (at least 0.8.0, not sure if it was already with 0.7.4).
