### ISSUE TITLE
Dialog asking about reboot after admin settings "Save"

### ISSUE THREAD

**Issue by viliman** [rameplayerorg/rameplayer-webui#30]
The changes that you made require reboot. Reboot or cancel the changes?

**Comment by iqqmuT** [comment]
Should there be option 'Restart later'? If for some reason the user wants to do something else too before restarting? In that case there could be a permanent toastr visible about the needed restart.

**Comment by viliman** [comment]
This is how it now pretty much works...

I think there is these options:
1. Restart needed flag is raised and the user restarts manually from switch (current implementation)
no changes to anything if this is ok.
2. User is asked about the restart and user can do the changes and restart or the changes are cancelled (my proposal). Benefit there are no pending settings that are forgotten, which is very likely to happen.
3. There is a restart button in the UI that the user can press after saving the settings. This I don't prefer because the user should have no other need of restarting the device except setting change, firmware upgrade (which reboots automatically)

**Comment by viliman** [comment]
@McLad76 or @jlauha any comments?
