### ISSUE TITLE
Missing link to browse back to parent folder

### ISSUE THREAD

**Issue by jlauha** [rameplayerorg/rameplayer-webui#32]
Regression in v0.8.0: the link for clicking to move back to parent folder is missing.

It used to be like this: e.g. "sda1 / subfolder", and clicking sda1 would return to root level. Now there's only " / subfolder".
(However, reloading webpage lets start over again from the root level.)

**Comment by iqqmuT** [comment]
Name field seems to be empty in backend response for the directory:
```
{"type":"device","size":16384,"uri":"file:\/\/5516-B377\/","modified":0,"items":...
"title":"KINGSTON","name":"","id":"5516-B377","refreshed":15000051}
```
It's used for breadcrumbs.
