### ISSUE TITLE
BUG: "no available firmwares" notification is not dealt properly

### ISSUE THREAD

**Issue by viliman** [rameplayerorg/rameplayer-webui#36]
If RamePlayer is not internet, upgrade responds with “no available firmwares” and WebUI gets confused leading to Exception: TypeError: e.value.split is not a function.

It would be good if there would be indication in the list of firmwares that there is no "No Internet Access!"

**Comment by foilharp** [comment]
Fixes on backend side.

**Comment by iqqmuT** [comment]
[commit](https://github.com/rameplayerorg/rameplayer-webui/commit/1a1a7af15e4e9d0bf4faac9e208ebd7e4922ae0a)
